services:
    icap_reference.form_manager: 
        class: Icap\ReferenceBundle\Service\FormManager
        arguments: [@service_container]

    #TODO see if useless
    icap_reference.choose_type:
        class: Icap\ReferenceBundle\Form\ChooseReferenceType
        arguments: [@service_container]

    icap_type.reference_default: 
        class: Icap\ReferenceBundle\Form\Reference\DefaultType
        arguments: []
        tags:
            - { name: form.type, alias: default }

    icap_type.reference_bibliography: 
        class: Icap\ReferenceBundle\Form\Reference\BibliographyType
        arguments: []
        tags:
            - { name: form.type, alias: bibliography }

    icap_type.reference_filmography: 
        class: Icap\ReferenceBundle\Form\Reference\FilmographyType
        arguments: []
        tags:
            - { name: form.type, alias: filmography }

    icap_type.reference_discography: 
        class: Icap\ReferenceBundle\Form\Reference\DiscographyType
        arguments: []
        tags:
            - { name: form.type, alias: discography }